version: "1.0"

stages:
  - "checkout"
  - "build"

steps:
  checkout:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"
    stage: "checkout"

  build:
    title: Installing Dependencies
    type: freestyle
    arguments:
      image: 'ubuntu:latest'
      commands:
        - apt update -qq && apt install -qy composer
        - composer install
